### ISSUE TITLE
local variable 'i' referenced before assignment 

### ISSUE THREAD

**Issue by Perseus1993** [astorfi/lip-reading-deeplearning#12]
when i run test.py :

`  File "test.py", line 576, in <module>
    tf.app.run()
  File "/home/ligen/anaconda2/envs/python3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "test.py", line 401, in main
    with tf.name_scope('%s_%d' % ('tower', i)) as scope:
UnboundLocalError: local variable 'i' referenced before assignment
`

**Comment by astorfi** [comment]
Thank you for pointing out the issue.
Please check if it is resolved now.
Moreover, please make sure to run the `train.py` at first for having some checkpoint to load.

**Comment by Perseus1993** [comment]
Yes. it works! Cheers buddy!!

**Comment by astorfi** [comment]
@Perseus1993 Ok Cool!
