### ISSUE TITLE
error when changing the input size

### ISSUE THREAD

**Issue by Perseus1993** [astorfi/lip-reading-deeplearning#14]
I changed the input image size into:  'mouth': np.random.random_sample(size=(num_training_samples, 9, 64, 64, 1))

then the error
Negative dimension size caused by subtracting 5 from 3 for 'tower_0/mouth_cnn/fc5/fc5_1/convolution' (op: 'Conv3D') with input shapes: [?,9,3,3,128], [1,2,5,128,256]

How should I change the net structure to fix that? thank you

**Comment by astorfi** [comment]
You should have an architecture regarding your input shape. I do not know what architecture can fit your input but the architecture related to your visual network must be changed.

**Comment by Perseus1993** [comment]
already fixed it, after looking into network structures

**Comment by astorfi** [comment]
OK cool
