### ISSUE TITLE
ValueError: not enough values to unpack (expected 6, got 3)

### ISSUE THREAD

**Issue by kpkool1995** [astorfi/lip-reading-deeplearning#15]
Hi,
Thanks for the project, please let me know which version of tensorflow you are using for the project, as I am getting "ValueError: not enough values to unpack (expected 6, got 3)" in train and test.py files at sess.run(). maybe there is a compatibility issue. P.S: I am using Windows machine.

**Comment by astorfi** [comment]
@kpkool1995   Thanks for pointing it out. I am guessing it is not the version problem because the project is passed continuous integration ([link](https://travis-ci.org/astorfi/lip-reading-deeplearning)) which supports the latest version. Let me check that.

**Comment by astorfi** [comment]
Please re-open this issue if the problem has not been resolved!
