### ISSUE TITLE
Visual Network - Input Size

### ISSUE THREAD

**Issue by ghost** [astorfi/lip-reading-deeplearning#16]
How to change the input size of visual network  to 112x112 (square) as an example?

**Comment by ghost** [comment]
I solved the problem by changing this line

`net = slim.repeat(net, 1, slim.conv2d, 256, [1, 2, 5], padding='VALID', scope='fc5')`

to this 

`net = slim.repeat(net, 1, slim.conv2d, 256, [1, 5, 5], padding='VALID', scope='fc5')`

**Comment by astorfi** [comment]
@nooshin85 Ok sounds good ... Please make sure to adjust the network architecture regarding your input size.
