### ISSUE TITLE
./results/mouth/frame_%*.png: could not find codec parameters

### ISSUE THREAD

**Issue by xiaoyun4** [astorfi/lip-reading-deeplearning#2]
Hi:
i am glad to find this source but when i run ./run.sh or ./lip_tracking_demo.sh, the error is:
[image2 @ 0x1aa4100] Could not open file : ./results/mouth/frame_*.png
[image2 @ 0x1aa4100] Could not find codec parameters (Video: png)
./results/mouth/frame_%*.png: could not find codec parameters

beacuse the results/mouth/frame_%*.png can't be find.  Can you release this file or give me an example what form the frame_%*.png is? if the frame_%*.png is only the part of mouth just like 'lip-reading-deeplearning-master/readme_images/1.gif '

**Comment by astorfi** [comment]
@xiaoyun4 Thank you for pointing out this issue ... I am investigating this case and get back to you very soon.

**Comment by astorfi** [comment]
@xiaoyun4 The sample video has been provided. Are you sure that you are correctly running the file of "./code/lip_tracking/VisualizeLip.py"? The ./run.sh file automatically run it but it won't stop if you get errors in running "./code/lip_tracking/VisualizeLip.py" for lack of the associated dependencies or etc. Would you please copy your whole command line here? e.g. after running ./run.sh.
Thanks

**Comment by astorfi** [comment]
Please activate it if the issue has not been resolved!
