### ISSUE TITLE
Number of filters

### ISSUE THREAD

**Issue by ir0nt0ad** [astorfi/lip-reading-deeplearning#22]
I may be mistaken, but shouldn't we be creating 128, not 64 filters here? The comment below says `shape=(?, 9, 128)`; we also had 128 in the previous layer.

https://github.com/astorfi/lip-reading-deeplearning/blob/6fe954015b796f70daa137c5c266f230a37ab6b2/code/training_evaluation/nets/lipread_speech.py#L138
https://github.com/astorfi/lip-reading-deeplearning/blob/6fe954015b796f70daa137c5c266f230a37ab6b2/code/training_evaluation/nets/lipread_speech.py#L145

**Comment by astorfi** [comment]
That does not make a huge difference.
