### ISSUE TITLE
How to synchronize your audio and image frame?

### ISSUE THREAD

**Issue by ss87021456** [astorfi/lip-reading-deeplearning#3]
Hello,
I wonder to know that how do you deal with the lip-movement frame and audio synchronization?
Since the input FPS may vary from videos to videos, e.g. 30 FPS means 33ms per frame, so each frame will represent 33ms audio. How do you deal with the video-audio corresponding pair?

**Comment by astorfi** [comment]
We took 0.3-sec synced frames that each of them consists 15 audio frames and 9 video frames and they are correspondent. Please refer to the paper for further details (Section IV).

**Comment by jigyasubagai** [comment]
Okies Thanks
