### ISSUE TITLE
Help in Lip reading

### ISSUE THREAD

**Issue by hasanagh** [astorfi/lip-reading-deeplearning#5]
Mr.Torfi,
May you please help me in lip-reading? I am able to detect the lips but what is the next step?
sorry for the inconvenience and really thank you. I am really interested in your work.

**Comment by astorfi** [comment]
@hasanagh Thank you so much for your interest. This project is not merely a tutorial nor an independent project. It is the implementation of its associated paper. Please make sure to read the paper at first, and I would be happy to guide you through different parts. Moreover, please read the [Contributing Section](https://github.com/astorfi/lip-reading-deeplearning/blob/master/CONTRIBUTING.rst).

Thank you so much for your help and support.
