### ISSUE TITLE
Can Your Current Implementation Synthesize Lip Movement Using Audio As Input?

### ISSUE THREAD

**Issue by MXGray** [astorfi/lip-reading-deeplearning#6]
Thanks for your awesome work! I just want to clarify if your current implementation can produce lip movement video output from audio input? i.e. Audio to lip movement video. Or, does your code need to be modified to do this? Please advise. Thanks again!  :)

**Comment by astorfi** [comment]
@MXGray Thanks for the kind words ... Ideally, if the error would be zero (which is not!), it should be able to do it. So basically, the design is for matching purposes and not the generation. Possibly, using GANs (Generative adversarial networks) may do your desired task in a better way.

Bests
