### ISSUE TITLE
about the demo

### ISSUE THREAD

**Issue by crazygirl1992** [astorfi/lip-reading-deeplearning#7]
hello,i run your code,and see the demo,the paper tell about the audio and video's synchronization.but why the demo is lip_tracking ,how can i see  the audio and video's effect of synchronization?and the training data how can i find .

**Comment by crazygirl1992** [comment]
hello,i run your code,and see the demo,the paper tell about the audio and video's synchronization.but why the demo is lip_tracking ,how can i see the audio and video's effect of synchronization?and the training data how can i find . @astorfi

**Comment by astorfi** [comment]
@crazygirl1992 Thanks for your attention ... There are two kinds of DEMOs. ``Training/Evaluation`` DEMO [(link)](https://asciinema.org/a/kXIDzZt1UzRioL1gDPzOy9VkZ) and ``Lip Tracking`` DEMO [(link)](https://asciinema.org/a/RiZtscEJscrjLUIhZKkoG3GVm). Both are available on the main page of the repository.
Let me know if any further information is needed.
