### ISSUE TITLE
Where to find MFEC api?

### ISSUE THREAD

**Issue by bg193** [astorfi/lip-reading-deeplearning#9]
Thanks for your awesome work! I 'm not find MFEC implementation in Speechpy, could you tell me where to get it, thank you!!

**Comment by astorfi** [comment]
@xuehui Thank you for your interest. MFEC is a naming convention which has been used for the paper [3D Convolutional Neural Networks for Cross Audio-Visual Matching Recognition](http://ieeexplore.ieee.org/document/8063416/). In [SpeechPy](https://github.com/astorfi/speechpy) if your refer to [Official Project Documentation](http://speechpy.readthedocs.io/en/latest/) it is called **Log Mel Frequency Energy** and is available in [this section](http://speechpy.readthedocs.io/en/latest/content/features.html).

Please let me know if you needed more information.
Regards
